// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv6Gz1dQ4BclCHtxlKHSxDbTRgr6KwnP0',
    appId: '1:265699502513:web:867c46fb55d0dcd267b590',
    messagingSenderId: '265699502513',
    projectId: 'notes-app-firebase-b237b',
    authDomain: 'notes-app-firebase-b237b.firebaseapp.com',
    storageBucket: 'notes-app-firebase-b237b.firebasestorage.app',
    measurementId: 'G-59B1FM62WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KvwVAqgzB3T3VwdZhQHAd-SWDVB5ZqY',
    appId: '1:265699502513:android:b1c53df7cb7e229f67b590',
    messagingSenderId: '265699502513',
    projectId: 'notes-app-firebase-b237b',
    storageBucket: 'notes-app-firebase-b237b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDplADrChxHKgD79Xz8Q_EZZuvWFmyIOo',
    appId: '1:265699502513:ios:83d06871692230e367b590',
    messagingSenderId: '265699502513',
    projectId: 'notes-app-firebase-b237b',
    storageBucket: 'notes-app-firebase-b237b.firebasestorage.app',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDplADrChxHKgD79Xz8Q_EZZuvWFmyIOo',
    appId: '1:265699502513:ios:83d06871692230e367b590',
    messagingSenderId: '265699502513',
    projectId: 'notes-app-firebase-b237b',
    storageBucket: 'notes-app-firebase-b237b.firebasestorage.app',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv6Gz1dQ4BclCHtxlKHSxDbTRgr6KwnP0',
    appId: '1:265699502513:web:9266ce2d63c0748a67b590',
    messagingSenderId: '265699502513',
    projectId: 'notes-app-firebase-b237b',
    authDomain: 'notes-app-firebase-b237b.firebaseapp.com',
    storageBucket: 'notes-app-firebase-b237b.firebasestorage.app',
    measurementId: 'G-R14B2JE5Z7',
  );
}
